### ISSUE TITLE
Toggle sometimes does not release the Windows Key

### ISSUE THREAD

**Issue by mattwright324** [Tylemagne/Gopher360#80]
This does not happen all of the time but frequently enough that I have begun to press the W key after toggling Gopher off to check if the Windows key is 'stuck' as in was not released. With the Start button linked to the Windows Key, could it a mixup of timing of which button pressed down first when pressing both Start and Back to toggle? 

Its not really an issue when Gopher is on, only when toggling it off and I go back to using the computer normally, typing with the keyboard, and it activating Windows Key + \<key\> combinations in the process. It's relatively simple to fix manually by just pressing the Windows Key once to trigger the button release but still annoying to have to check.

**Comment by kkaja123** [comment]
Yes, this is due to the way that all key presses are handled. Each key has a pressed and release state. These two states are mapped to the same two states of the gamepad's buttons. When Gopher toggles off, it doesn't detect that the gamepad button is released, so it doesn't release the Windows key (in your case). For now, the workaround would be to change the button mapping in the config.ini file such that the toggle Gopher function is mapped to buttons that have no other mappings.

I will work up a fix to have Gopher release any keys that it is pressing when toggling it off. FYI, I don't know when the next release will be, so you will have to work around it or download the code to compile the application on your own, when the fix is in.
